# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Transition State Probability
#' 'gamma_gt' computes the transition probability matrix
#'
#' @param R integer number of marked individuals released per occasion
#' @param phi double number. Survival probability of individuals
#' @param cores The number of cores on your machine.
#' @return pR Returns the transition matrix
#' @name gamma_gt
NULL

gamma_gt <- function(R, phi) {
    .Call(`_extBatchMarking_gamma_gt`, R, phi)
}

